# 5 lines of code for a map[^1]

## Load Data
```{r loaddata}
starbucks <- read_csv("../data/NC_Starbucks_Locations.csv")

# Original documentation provided the following 2-line method and gathered data for the whole US.  But there were two problems affecting convenience.  One, the data were large (over 10,000 rows) causing the map-making package, leaflet, to be painfully slow.  Two, the data were so profoundly messy that I decided to clean it in openrefine (<http://openrefine.org>), then limit the data to NC.  As demonstrated below, you can import this data into [R] without my initial cleaning step.  
## file <- "https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv"
## starbucks <- read.csv(file)
```

## Make the Map
```{r makemap}
require(leaflet); library(magrittr)
leaflet() %>% addTiles() %>% setView(-78.8310, 35.9867, zoom = 10) %>% 
  addMarkers(data = starbucks, lat = ~ Latitude, lng = ~ Longitude, popup = starbucks$Name)
```

####Credit: 
[^1]: [5 Visualizations in 5 Minutes](http://www.computerworld.com/article/2893271/business-intelligence/5-data-visualizations-in-5-minutes-each-in-5-lines-or-less-of-r.html). ComputerWorld.com by Sharon Machlis
